name: "godot-ci export"

on:
  push:
    tags:
      - 'v*'

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: LudumDare51

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p build/linux build/windows ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Windows Build
        run: godot -v --export-debug "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p build/linux build/windows ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Linux Build
        run: godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux

  release:
    name: Make release
    runs-on: ubuntu-latest
    needs: [export-windows, export-linux]
    steps:
      - 
        name: Download windows build
        uses: actions/download-artifact@v2
        with:
          name: windows
          path: cammy_devnull_ld51_win
      - 
        name: Download linux build
        uses: actions/download-artifact@v2
        with:
          name: linux
          path: cammy_devnull_ld51_linux
      -
        name: Zip it
        run: |
          zip -o cammy_devnull_ld51_win.zip cammy_devnull_ld51_win/**
          zip -o cammy_devnull_ld51_linux.zip cammy_devnull_ld51_linux/**
      - 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cammy_devnull_ld51_linux.zip,cammy_devnull_ld51_win.zip"
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}
